### ISSUE TITLE
[BE]위치 관련 기능을 개발한다.

### ISSUE THREAD

**Issue by ansdudgh98** [Team-studywithme/studyWithMe-BackEnd#34]
**기능**
내 현재 위치 저장하기
내 현재 위치를 기준으로 원하는 거리내에 유저 좌표 불러오기
테스트 데이터 생성

**테스트데이터 추가**
내 현재 위치 저장하는 API를 호출하면 API호출과 동시에 원하는 거리내에 유저 좌표를 불러오도록 테스트 데이터 생성을 진행함

**Comment by chahyoungseok** [comment]
도메인 담당이 바뀌어, 도메인 재 이해 후 리팩토링 예정
